In [ ]:
import numpy as np

In [ ]:
#Создайте массив из 10 нулей
arr0=np.zeros(10)
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#Создать массив из 10 единиц
arr1=np.ones(10)
print(arr1)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#Создать массив из 10 пятерок
arr5=np.zeros(10)
arr5[...]=5
print(arr5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
#Создать массив из целых чисел от 10 до 50
a=np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [ ]:
#Создать массив из четных чисел от 10 до 50
a2=np.arange(10,51,2)
print(a2)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
#Создать матрицу 3х3 с числами от 0 до 8
m=np.arange(0,9)
m=m.reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#Создать единичную матрицу 3x3
m1=np.eye(3)
print(m1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#Используйте NumPy для генерации случайного числа от 0 до 1
k=np.random.rand(1)
print(k)

[0.37741742]


In [ ]:
#Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
arrn=np.random.randn(25)
print(arrn)

[-3.67705658e-01  4.53679632e-01  1.19947803e+00 -3.03335257e-01
 -1.98361556e-01  4.35144129e-01  4.97502964e-01 -2.97142446e-01
 -2.89051171e-01  6.25975859e-01  2.02060312e-01 -1.49571857e-03
  1.66826013e+00 -7.41325163e-01  1.94224270e-01  2.28633737e-01
 -6.79557921e-01  1.47344739e+00  1.30520489e+00 -2.90294379e-01
 -2.27638598e+00 -1.39624761e+00  6.17447988e-01 -4.34124334e-01
  9.59473941e-01]


In [ ]:
#Создайте следующую матрицу используя функции библиотеки NumPy:
m2=np.arange(0.01,1.01,0.01)
m2=m2.reshape(10,10)
print(m2)


[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)
print('---------------------')
print('array',mat[2:,1:])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
---------------------
array [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
#Написать код обращения к элементу который вернет значение  20 из стартовой матрицы задачи l
print(mat[3,4])

20


In [ ]:
print('array',mat[:3,1].reshape(3,1))

array [[ 2]
 [ 7]
 [12]]


In [ ]:
print('array',mat[4])

array [21 22 23 24 25]


In [ ]:
print('array',mat[3:])

array [[16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#Получить сумму всех значений в стартовой матрице mat
print(mat.sum())

325


In [ ]:
#Получить стандартное отклонение в стартовой матрице mat
print(mat.std())

7.211102550927978


In [ ]:
#Получить сумму значений в колонках в стартовой матрице mat
print(mat.sum(axis=0))

[55 60 65 70 75]
